Generate token
WildCodeSchool/did-you-beat-it-backend pull request #7
Opened 2024-07-03 15:28 UTC by Sid-Ahmed7

Add token
Config spring security
update login and register

2024-07-03 16:23 UTC, Marwasliti approved these changes

2024-07-04 08:32 UTC, Benja-san requested changes

2024-07-04 08:32 UTC, Benja-san commented on src/main/java/com/example/demo/config/SecurityConfiguration.java
> +                .requestMatchers("/users/*").permitAll()
if you allow all users to go to route /users/** they'll be able to consult any data from any users, and access to post / update /delete route

2024-07-04 08:41 UTC, Benja-san approved these changes

2024-07-04 08:41 UTC, merged