create score table
WildCodeSchool/did-you-beat-it-backend pull request #8
Opened 2024-07-03 16:36 UTC by Azagi

2024-07-04 07:14 UTC, Marwasliti approved these changes

2024-07-04 08:35 UTC, Benja-san requested changes

2024-07-04 08:35 UTC, Benja-san commented on src/main/java/com/example/demo/controller/ScoreController.java
> +        Score score = scoreOptional.get();
shift all update logic in an update method from scoreService

2024-07-04 08:35 UTC, Benja-san commented on src/main/java/com/example/demo/entity/Score.java
> +    private Long UserId;
remember to join tables as soon as you can

2024-07-09 07:43 UTC, Benja-san approved these changes

2024-07-09 08:06 UTC, merged